[package]
name = "bundle-test-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jito_be"

[[bin]]
name = "jito_validator"

[dependencies]
bincode = "1.3.3"
bs58 = "0.5"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
futures = "0.3"
futures-util = "0.3"
log = "0.4"
prost = "0.14"
prost-types = "0.14"
rand = "0.9.1"
solana-client = "3"
solana-commitment-config = "3"
solana-compute-budget-interface = "3.0.0"
solana-keypair = "3"
solana-sdk = "3"
solana-system-interface = { version = "3", features = ["bincode"] }
spl-memo = "6.0.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
tokio-stream = "0.1"
tonic = { version = "0.14" }
tonic-prost = { version = "0.14" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "fast-rng"] }

[build-dependencies]
tonic-prost-build = "0.14"
